const GET_COUNTER_REQ = 'GET_COUNTER_REQ';
const GET_COUNTER_SUCCESS = 'GET_COUNTER_SUCCESS';
const INCREMENT_REQ = 'INCREMENT_REQ';
const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS';
const DECREMENT_REQ = 'DECREMENT_REQ';
const DECREMENT_SUCCESS = 'DECREMENT_SUCCESS';


export {
    GET_COUNTER_REQ,
    GET_COUNTER_SUCCESS, 
    INCREMENT_REQ,
    INCREMENT_SUCCESS,
    DECREMENT_REQ,
    DECREMENT_SUCCESS
}